"""
DJZ-Speak ComfyUI Node Package
Robotic text-to-speech using eSpeak-NG formant synthesis
"""

from .DJZ_Speak_v1 import NODE_CLASS_MAPPINGS as DJZ_SPEAK_V1_MAPPINGS
from .DJZ_Speak_v1 import NODE_DISPLAY_NAME_MAPPINGS as DJZ_SPEAK_V1_DISPLAY_MAPPINGS

from .DJZ_Speak_v2 import NODE_CLASS_MAPPINGS as DJZ_SPEAK_V2_MAPPINGS
from .DJZ_Speak_v2 import NODE_DISPLAY_NAME_MAPPINGS as DJZ_SPEAK_V2_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

# Register DJZ-Speak v1 nodes
NODE_CLASS_MAPPINGS.update(DJZ_SPEAK_V1_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(DJZ_SPEAK_V1_DISPLAY_MAPPINGS)

# Register DJZ-Speak v2 nodes
NODE_CLASS_MAPPINGS.update(DJZ_SPEAK_V2_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(DJZ_SPEAK_V2_DISPLAY_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
